# Generated by Django 4.0.4 on 2022-06-03 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemTag',
            new_name='TaggedItem',
        ),
    ]
